name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  lint:
    name: Lint code
    runs-on: [ubuntu-latest]
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Get yarn cache dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Get yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install yarn deps
        run: yarn install
      - name: Run lint
        run: yarn lint

  test:
    name: Run tests with node ${{ matrix.node_version }} on ${{ matrix.os }}
    runs-on: [ubuntu-latest]
    needs: lint
    strategy:
      matrix:
        node_version: ['10', '12']
        os: [ubuntu-latest]
    steps:
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Get yarn cache dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Get yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install yarn deps
        run: yarn install
      - name: Run tests
        run: yarn test
